Repository pieh/merge-on-green-playground, pull requests merged in 2019-06, with the labels that each got.

#1 test
  index.js
Labels: bot: merge on green, help wanted

#2 Update index.js
  index.js
Labels: bot: merge on green

#3 Update index.js
  index.js
Labels: bot: merge on green

#4 make it break
  index.js
Labels: bot: merge on green, bug

#5 make it break again
  index.js
Labels: bot: merge on green

#7 make it break forever
  index.js
Labels: bot: merge on green

#8 make it slower
  index.js
Labels: bot: merge on green

#9 Update README.md yay
  README.md
Labels: bot: merge on green

#10 Update index.js
  index.js
Labels: bot: merge on green
